### ISSUE TITLE
Syntax hilighting for msbuild log

### ISSUE THREAD

**Issue by farnyser** [tillig/SublimeMSBuild#13]
Hello,
Could you add support for highlighting build log produced by MSBuild ?
It would be great :)

**Comment by tillig** [comment]
Unfortunately, I'm probably not going to be able to address this one for a couple of reasons.

First, Sublime uses file extensions to map syntax to files. The extension ".log" has... a lot of meanings. You'd have to "know" to switch syntax or that it's even an option.

Second, the contents of the build log change based on verbosity. Like if you switch from normal to verbose to debug, the log changes. It'd be pretty tough to handle all of those.

Third, and probably most important... The majority of the log output is actually from tools like the C# compiler (csc.exe) and not MSBuild. There's no way I'd be able to cover all the tools people use.

Anyway... Interesting idea, but I don't think I'll be able to help. I'd rather spend my limited time on making sure the build file highlighting works.
