### ISSUE TITLE
UsingTask auto completion error

### ISSUE THREAD

**Issue by Shuliyey** [tillig/SublimeMSBuild#14]
Hi,

The using task auto completion syntax have changed.

from 

\<UsingTask TaskName="" AssemblyName=""\>

to

\<UsingTask TaskName="" AssemblyFile=""\>

the code base auto completion still got the old one.

I think the code is at msbuild_completion.py line 460.

**Comment by tillig** [comment]
[Per the docs](https://msdn.microsoft.com/en-us/library/t41tzex2(v=vs.140).aspx), you can use _either_ `AssemblyName` _or_ `AssemblyFile`. Looks like this has been the case for quite some time.

That said, I think you're right in that `AssemblyFile` is probably the more common of the usage scenarios so I'll see what I can do about getting this updated. Thanks!

**Comment by tillig** [comment]
Updated and should be out in version 1.2.5.

**Comment by Shuliyey** [comment]
Thank you so much :)
