### ISSUE TITLE
More complete file_regex

### ISSUE THREAD

**Issue by cjo20** [tillig/SublimeMSBuild#3]
Using VS2012 express, the existing file_regex doesn't capture the error message to display in the status bar at the bottom. It also doesn't deal with files that start with .\ when searching through the errors.

Something like:

^[\t ]_(?:\.\\)?(._)\(([0-9]_)\)():(._) \[

Might work better. It swallows the whitespace at the start of the line, removes the .\ if there is one, then captures the filename, followed by the line number. VS2012 express doesn't seem to output a column number. Lastly the error message is captured, ending at the [ before the project file name.

**Comment by aguscha333** [comment]
Hi, I have this king of error mesage:
[C:\prog2\tarea3\src\ColaPrioridad.mod 58.13 E088]
does somebody know how would the file_regex for that would be?? I'm completely lost with this.
